#!/bin/csh

# foreach t ( 1 2 4 )
#     foreach n ( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 )
# 	echo "Fix #1"
# 	echo NUMT = $t
# 	echo NUM = $n
# 	g++ -DNUMT=$t -DNUM=$n prj3.cpp -o prog -lm -fopenmp
# 	./prog
#     end
# end

foreach t ( 1 2 4 )
	echo "Fix #2"
	echo NUMT = $t
	g++ -DNUMT=$t prj3.cpp -o prog -lm -fopenmp
	./prog
end
